import type { Locale } from './i18n';

const copy = {
  'zh-TW': {
    back: '返回首頁',
    modelProfile: '模型資料',
    benchmarkProfile: 'Benchmark 資料',
    provider: '供應商',
    family: '模型家族',
    releaseDate: '發布日期',
    lifecycle: '生命週期',
    contextWindow: '上下文窗口',
    parameters: '參數量',
    openWeights: '開放權重',
    yes: '是',
    no: '否',
    unknown: '未提供',
    currentSnapshot: '目前快照',
    coverage: '覆蓋率',
    history: 'Edition 歷史',
    results: '原始 Benchmark 結果與證據',
    edition: 'Edition',
    rank: '排名',
    score: '總分',
    status: '狀態',
    metric: 'Metric',
    value: '數值',
    sampleSize: '樣本數',
    evidence: '主要證據',
    qualityFlags: '資料品質標記',
    none: '無',
    noResults: '目前沒有已發布結果。',
    version: '版本',
    license: '授權',
    methodology: '方法學',
    homepage: '官方首頁',
    metrics: 'Metrics 定義',
    direction: '方向',
    range: '理論範圍',
    higher: '越高越好',
    lower: '越低越好',
    leaderboard: '各 Metric 前 10 名',
    model: '模型',
    details: '查看模型詳情',
  },
  en: {
    back: 'Back to home',
    modelProfile: 'Model profile',
    benchmarkProfile: 'Benchmark profile',
    provider: 'Provider',
    family: 'Model family',
    releaseDate: 'Release date',
    lifecycle: 'Lifecycle',
    contextWindow: 'Context window',
    parameters: 'Parameters',
    openWeights: 'Open weights',
    yes: 'Yes',
    no: 'No',
    unknown: 'Not provided',
    currentSnapshot: 'Current snapshot',
    coverage: 'Coverage',
    history: 'Edition history',
    results: 'Raw benchmark results and evidence',
    edition: 'Edition',
    rank: 'Rank',
    score: 'Overall score',
    status: 'Status',
    metric: 'Metric',
    value: 'Value',
    sampleSize: 'Sample size',
    evidence: 'Primary evidence',
    qualityFlags: 'Quality flags',
    none: 'None',
    noResults: 'No published results are available.',
    version: 'Version',
    license: 'License',
    methodology: 'Methodology',
    homepage: 'Official homepage',
    metrics: 'Metric definitions',
    direction: 'Direction',
    range: 'Theoretical range',
    higher: 'Higher is better',
    lower: 'Lower is better',
    leaderboard: 'Top 10 per metric',
    model: 'Model',
    details: 'View model details',
  },
} as const;

export const getDetailCopy = (locale: Locale) => copy[locale];
