import {
  DIMENSION_IDS,
  RankingSnapshotSchema,
  type DimensionId,
} from '@llm-bench/contracts';

const createDimensions = (scores: Record<DimensionId, number>) =>
  DIMENSION_IDS.map((dimension) => ({
    dimension,
    score: scores[dimension],
    coverage: 0.68,
    confidence: 72,
    status: 'PROVISIONAL' as const,
  }));

export const previewSnapshot = RankingSnapshotSchema.parse({
  id: '019f513f-132a-7dc0-805d-0b036ea0d475',
  editionDate: '2026-07-11',
  dataCutoffAt: '2026-07-11T12:30:00.000Z',
  scoringMethodVersion: 'preview-ui-v1',
  sourceSnapshotIds: ['019f513f-132a-7dc0-805d-0b036ea0d476'],
  entries: [
    {
      modelVariantId: '019f513f-132a-7dc0-805d-0b036ea0d477',
      slug: 'orion-3-2-reasoner',
      displayName: 'Orion 3.2 Reasoner',
      providerName: 'Northstar Preview',
      rank: 1,
      overallScore: 78.4,
      overallCoverage: 0.72,
      overallConfidence: 76,
      rankingStatus: 'PROVISIONAL',
      dimensions: createDimensions({
        reasoning: 91,
        math: 88,
        knowledge: 76,
        language: 82,
        instruction: 74,
        coding: 71,
        agentic: 66,
        context: 79,
      }),
      qualityFlags: ['PROVISIONAL'],
    },
    {
      modelVariantId: '019f513f-132a-7dc0-805d-0b036ea0d478',
      slug: 'helix-pro',
      displayName: 'Helix Pro',
      providerName: 'Vector Preview',
      rank: 2,
      overallScore: 75.9,
      overallCoverage: 0.69,
      overallConfidence: 73,
      rankingStatus: 'PROVISIONAL',
      dimensions: createDimensions({
        reasoning: 80,
        math: 74,
        knowledge: 83,
        language: 87,
        instruction: 81,
        coding: 63,
        agentic: 68,
        context: 75,
      }),
      qualityFlags: ['PROVISIONAL'],
    },
    {
      modelVariantId: '019f513f-132a-7dc0-805d-0b036ea0d479',
      slug: 'mosaic-code-xl',
      displayName: 'Mosaic Code XL',
      providerName: 'Foundry Preview',
      rank: 3,
      overallScore: 73.6,
      overallCoverage: 0.66,
      overallConfidence: 70,
      rankingStatus: 'PROVISIONAL',
      dimensions: createDimensions({
        reasoning: 75,
        math: 79,
        knowledge: 68,
        language: 71,
        instruction: 72,
        coding: 94,
        agentic: 82,
        context: 65,
      }),
      qualityFlags: ['PROVISIONAL'],
    },
    {
      modelVariantId: '019f513f-132a-7dc0-805d-0b036ea0d47a',
      slug: 'northstar-large',
      displayName: 'Northstar Large',
      providerName: 'Atlas Preview',
      rank: 4,
      overallScore: 70.8,
      overallCoverage: 0.64,
      overallConfidence: 68,
      rankingStatus: 'PROVISIONAL',
      dimensions: createDimensions({
        reasoning: 69,
        math: 64,
        knowledge: 86,
        language: 78,
        instruction: 76,
        coding: 61,
        agentic: 60,
        context: 72,
      }),
      qualityFlags: ['PROVISIONAL'],
    },
  ],
});
